ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-artifact-delete_{context}']
= rhoas service-registry artifact delete

[role="_abstract"]
[beta] Deletes all of the artifacts that exist in a given group

[discrete]
== Synopsis


Deletes all of the artifacts that exist in a given group. 

Delete command works in two modes:

	- When --artifact argument is missing delete will delete all artifacts in the group
	- When --artifact is specified delete deletes only single artifact and its version

When --group parameter is missing the command will create a new artifact under the "default" group.
		
This command is available as part of the developer preview


....
rhoas service-registry artifact delete [flags]
....

[discrete]
== Examples

....

## Delete all artifacts in the group "default"
rhoas service-registry artifact delete 

## Delete artifact in the group "default" with name "my-artifact"
rhoas service-registry artifact delete my-artifact
		
....

[discrete]
== Options

  `-a`, `--artifact` _string_::    Id of the artifact
  `-g`, `--group` _string_::       Group of the artifact
      `--instance-id` _string_::   Id of the registry to be used. By default uses currently selected registry
  `-o`, `--output` _string_::      Format in which to display the Service Registry instance (choose from: "json", "yml", "yaml") (default "json")
  `-y`, `--yes`::                  Delete without prompt

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode
      `--version`::     Show rhoas version

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry_artifact.adoc#rhoas-service-registry-artifact[rhoas service-registry artifact]	 - [beta] Manage Service Registry Artifacts commands
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - [beta] Manage Service Registry Artifacts commands
endif::[]

