ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-artifact-update_{context}']
= rhoas service-registry artifact update

[role="_abstract"]
[alpha] Update artifact

[discrete]
== Synopsis

Update artifact from file or directly standard input

Artifacts can be typically in JSON format for most of the supported types, but may be in another format for a few (for example, PROTOBUF).
The type of the content should be compatible with the current artifact's type.

When successful, this creates a new version of the artifact, making it the most recent (and therefore official) version of the artifact.

An artifact is update using the content provided in the body of the request.
This content is updated under a unique artifactId provided by user.

This command is available as part of the developer preview


....
rhoas service-registry artifact update [flags]
....

[discrete]
== Examples

....
## update artifact from group and artifact-id
rhoas service-registry artifact update --artifact-id=my-artifact --group my-group my-artifact.json

## update artifact from group and artifact-id
rhoas service-registry artifact update --artifact-id=my-artifact --group my-group my-artifact.json

....

[discrete]
== Options

      `--artifact-id` _string_::   Id of the artifact
      `--description` _string_::   Custom description of the artifact
  `-f`, `--file` _string_::        File location of the artifact
  `-g`, `--group` _string_::       Artifact group (default "default")
      `--instance-id` _string_::   Id of the registry to be used. By default uses currently selected registry
      `--name` _string_::          Custom name of the artifact
  `-o`, `--output` _string_::      Format in which to display the Service Registry instance (choose from: "json", "yml", "yaml") (default "json")
      `--version` _string_::       Custom version of the artifact (for example 1.0.0)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry_artifact.adoc#rhoas-service-registry-artifact[rhoas service-registry artifact]	 - [alpha] Manage Service Registry Artifacts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - [alpha] Manage Service Registry Artifacts
endif::[]

