ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-artifact-get_{context}']
= rhoas service-registry artifact get

[role="_abstract"]
[beta] Get artifact by id and group

[discrete]
== Synopsis

Get artifact by specifying id and group.
Command will fetch the latest artifact from the registry based on the artifactId and group.

When --version is specified command will fetch the specific version of the artifact.
Get command will fetch artifacts based on group and artifactId and version.
For fetching artifacts using global identifiers please use "service-registry download" command

This command is available as part of the developer preview


....
rhoas service-registry artifact get [flags]
....

[discrete]
== Examples

....

## Get latest artifact by name
rhoas service-registry artifact get myschema

## Get latest artifact and save its content to file
rhoas service-registry artifact get myschema myschema.json

## Get latest artifact and pipe it to other command 
rhoas service-registry artifact get myschema | grep -i 'user'

## Get latest artifact by specifying custom group, registry and name as flag
rhoas service-registry artifact get --group mygroup --instance-id=myregistry --artifact myartifact

....

[discrete]
== Options

  `-a`, `--artifact` _string_::    Id of the artifact
  `-g`, `--group` _string_::       Group of the artifact
      `--instance-id` _string_::   Id of the registry to be used. By default uses currently selected registry
      `--output-file` _string_::   Filename of the output file

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode
      `--version`::     Show rhoas version

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry_artifact.adoc#rhoas-service-registry-artifact[rhoas service-registry artifact]	 - [beta] Manage Service Registry Artifacts commands
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - [beta] Manage Service Registry Artifacts commands
endif::[]

