ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-artifact-get_{context}']
= rhoas service-registry artifact get

[role="_abstract"]
[alpha] Get artifact by id and group

[discrete]
== Synopsis

Get artifact by specifying id and group.
Command will fetch the latest artifact from the registry based on the artifact-id and group.

When --version is specified command will fetch the specific version of the artifact.
Get command will fetch artifacts based on --group and --artifact-id and --version.
For fetching artifacts using global identifiers please use "service-registry download" command

This command is available as part of the developer preview


....
rhoas service-registry artifact get [flags]
....

[discrete]
== Examples

....
## Get latest artifact with name "my-artifact" and print it out to standard out
rhoas service-registry artifact get --artifact-id=my-artifact

## Get latest artifact with name "my-artifact" from group "my-group" and save it to artifact.json file
rhoas service-registry artifact get --artifact-id=my-artifact --group=my-group --output-file=artifact.json

## Get latest artifact and pipe it to other command
rhoas service-registry artifact get --artifact-id=my-artifact | grep -i 'user'

## Get artifact with custom version and print it out to standard out
rhoas service-registry artifact get --artifact-id=myartifact --version=4

....

[discrete]
== Options

      `--artifact-id` _string_::   Id of the artifact
  `-g`, `--group` _string_::       Artifact group (default "default")
      `--instance-id` _string_::   Id of the registry to be used. By default uses currently selected registry
      `--output-file` _string_::   Location of the output file
      `--version` _string_::       Version of the artifact

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry_artifact.adoc#rhoas-service-registry-artifact[rhoas service-registry artifact]	 - [alpha] Manage Service Registry Artifacts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - [alpha] Manage Service Registry Artifacts
endif::[]

